services:
  # eureka:
  #   build:
  #     context: ../EurekaServer
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8761:8761"
  #   networks:
  #     - app-network
  #   healthcheck:
  #     test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8761/actuator/health | grep -q UP"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s

  # app:
  #   build:
  #     context: ../ProductService
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     productMYSQL:
  #       condition: service_healthy
  #     eureka:
  #       condition: service_healthy
  #   environment:
  #     - SPRING_R2DBC_URL=r2dbc:mysql://productMYSQL:3306/productdb  # Đã sửa
  #     - SPRING_R2DBC_USERNAME=admin
  #     - SPRING_R2DBC_PASSWORD=password
  #     - SPRING_FLYWAY_URL=jdbc:mysql://productMYSQL:3306/productdb  # Đã sửa
  #     - SPRING_FLYWAY_USER=admin
  #     - SPRING_FLYWAY_PASSWORD=password
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
  #   networks:
  #     - app-network
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s

  productMYSQL:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=productdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s  # Tăng thời gian chờ cho MySQL
    ports:
      - "3306:3306"

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge