version: '3.8'

services:
  app:
    build:
      context: ../ProductService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - productMYSQL
    environment:
      - SPRING_R2DBC_URL=r2dbc:productMYSQL://mysql:3306/productdb
      - SPRING_R2DBC_USERNAME=admin
      - SPRING_R2DBC_PASSWORD=password
      - SPRING_FLYWAY_URL=jdbc:productMYSQL://mysql:3306/productdb
      - SPRING_FLYWAY_USER=admin
      - SPRING_FLYWAY_PASSWORD=password
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"] # Kiểm tra endpoint health
      interval: 30s  # Kiểm tra mỗi 30 giây
      timeout: 5s    # Timeout sau 5 giây nếu không phản hồi
      retries: 5     # Thử lại 5 lần trước khi coi là unhealthy
      start_period: 15s # Chờ 15s giây trước khi bắt đầu kiểm tra (cho app khởi động)

  productMYSQL:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=productdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-ppassword"] # Kiểm tra MySQL sống
      interval: 10s   # Kiểm tra mỗi 10 giây
      timeout: 5s     # Timeout sau 5 giây
      retries: 5      # Thử lại 5 lần
      start_period: 10s # Chờ 30 giây để MySQL khởi động

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge